### ISSUE TITLE
byte-code: Symbol’s function definition is void: magit-define-popup-keys-deferred

### ISSUE THREAD

**Issue by hhnr** [Wilfred/edit-it#2]
I have installed the refine package and when i try M-x refine it throws this error,

```
byte-code: Symbol’s function definition is void: magit-define-popup-keys-deferred
```

NOTE: I'm not entirely sure what your package does, i just wanted to try it out but couldn't. Also the gifs are not really helping me understand what your package does. A step by step action, what you are doing, what command you are giving and what the output looks like would be really easy to grasp for elisp newbs like me. Thanks

**Comment by Wilfred** [comment]
Strange. Are you sure that's an error? I'd have expected that to just be a warning.

Anyway, since the magit-popup functionality was an unfinished prototype, I've removed it.

**Comment by Wilfred** [comment]
I've also updated the introduction in the readme.:

> Refine provides a convenient UI for editing lists. Refine is not for
> editing files, but for changing elisp variables that are set to lists.

Does that help? If you have a variable in elisp that's a list, refine can help you modify that list. You can add, remove or reorder items in that list.

To use a Python analogy: suppose you're working in the interpreter:

``` python
>>> x
["foo", "bar", "bizbaz", "boz", "xxx", "yyy", "zzz"]
```

Now, suppose you want to change the list to `["foo", "bizbaz", "newitem", "boz", "yyy", "xxx", "zzz"]` You could work out which list indexes you need, to reorder, remove and add items. Or, you could open the data in a spreadsheet. Refine aims to be a little more interactive, like a spreadsheet.

Please let me know if that makes sense, I do want to make the README clear to newcomers.

**Comment by hhnr** [comment]
> Strange. Are you sure that's an error? I'd have expected that to just be a warning.

When i tried to run `M-x refine` the message was displayed in the minibuffer every time. So i thought it was an error.

> Now, suppose you want to change the list to ["foo", "bizbaz", "newitem", "boz", "yyy", "xxx", "zzz"] You >could work out which list indexes you need, to reorder, remove and add items. Or, you could open >the data in a spreadsheet. Refine aims to be a little more interactive, like a spreadsheet.

Thanks. It makes sense now.
